Pregunta 1

In [2]:
for i in range (1,16):
    s = 48 + 0.7*i
    print (f"el numero {i} es {s}")

el numero 1 es 48.7
el numero 2 es 49.4
el numero 3 es 50.1
el numero 4 es 50.8
el numero 5 es 51.5
el numero 6 es 52.2
el numero 7 es 52.9
el numero 8 es 53.6
el numero 9 es 54.3
el numero 10 es 55.0
el numero 11 es 55.7
el numero 12 es 56.4
el numero 13 es 57.1
el numero 14 es 57.8
el numero 15 es 58.5


Pregunta 2

In [4]:
for i in range (1,20):
    s = i**3 - 2*i
    print (f"el numero {i} es {s}")
    if s == 2171:
        print(i)

el numero 1 es -1
el numero 2 es 4
el numero 3 es 21
el numero 4 es 56
el numero 5 es 115
el numero 6 es 204
el numero 7 es 329
el numero 8 es 496
el numero 9 es 711
el numero 10 es 980
el numero 11 es 1309
el numero 12 es 1704
el numero 13 es 2171
13
el numero 14 es 2716
el numero 15 es 3345
el numero 16 es 4064
el numero 17 es 4879
el numero 18 es 5796
el numero 19 es 6821


Pregunta 3

In [12]:
for i in range (1,20):
    s = 140 + (i-1)*80
    print (f"actualizacion {i}: {s}")

actualizacion 1: 140
actualizacion 2: 220
actualizacion 3: 300
actualizacion 4: 380
actualizacion 5: 460
actualizacion 6: 540
actualizacion 7: 620
actualizacion 8: 700
actualizacion 9: 780
actualizacion 10: 860
actualizacion 11: 940
actualizacion 12: 1020
actualizacion 13: 1100
actualizacion 14: 1180
actualizacion 15: 1260
actualizacion 16: 1340
actualizacion 17: 1420
actualizacion 18: 1500
actualizacion 19: 1580


Pregunta 4

In [14]:
for i in range (1,20):
    s = 4 * 3**(i)
    print (f"gana {i} veces: {s}")

gana 1 veces: 12
gana 2 veces: 36
gana 3 veces: 108
gana 4 veces: 324
gana 5 veces: 972
gana 6 veces: 2916
gana 7 veces: 8748
gana 8 veces: 26244
gana 9 veces: 78732
gana 10 veces: 236196
gana 11 veces: 708588
gana 12 veces: 2125764
gana 13 veces: 6377292
gana 14 veces: 19131876
gana 15 veces: 57395628
gana 16 veces: 172186884
gana 17 veces: 516560652
gana 18 veces: 1549681956
gana 19 veces: 4649045868


Pregunta 5

In [3]:
for i in range (1,11):
    s = 900 - (i-1)*100
    print (f"al paso de {i} horas: {s}")

al paso de 1 horas: 900
al paso de 2 horas: 800
al paso de 3 horas: 700
al paso de 4 horas: 600
al paso de 5 horas: 500
al paso de 6 horas: 400
al paso de 7 horas: 300
al paso de 8 horas: 200
al paso de 9 horas: 100
al paso de 10 horas: 0


Pregunta 6

In [26]:
suma = 0
for i in range (1,13):
    s = 3 * 2**(i-1)
    suma += s
    print (f"mes {i}: {s}")
print ("total:", suma)

mes 1: 3
mes 2: 6
mes 3: 12
mes 4: 24
mes 5: 48
mes 6: 96
mes 7: 192
mes 8: 384
mes 9: 768
mes 10: 1536
mes 11: 3072
mes 12: 6144
total: 12285


Pregunta 9

In [31]:
import numpy as np

A = np.array([[-2, 5, -1],
              [-8, 4, 0]])

T = A.T
print(np.transpose(A))
print(T)

[[-2 -8]
 [ 5  4]
 [-1  0]]
[[-2 -8]
 [ 5  4]
 [-1  0]]


Pregunta 10

In [36]:
import numpy as np

#Sucursal 1
              #B   #N
A = np.array([[30, 50], #Cargador
              [25, 18], #Router
              [12, 16], #Cámara
              [9, 40]]) #Alexa

#Sucursal 2
              #B   #N
B = np.array([[10, 30], #Cargador
              [15, 27], #Router
              [24, 14], #Cámara
              [10, 22]]) #Alexa

C = A + B
print (C)


[[40 80]
 [40 45]
 [36 30]
 [19 62]]


Pregunta 11

In [1]:
import numpy as np

#Cantidad de productos enviados desde dos bodegas a tres destinos
              #D1   #D2  #D3
A = np.array([[150, 300, 250], #B1
              [250, 100, 200]]) #B2

#Costo de envío por producto (en miles de pesos) al destino i en el año j (2023 - 2024)
              #23 #24
B = np.array([[1, 3], #D1
              [2, 2], #D2
              [1, 3]]) #D3

C = np.dot(A, B)
print(C)


[[1000 1800]
 [ 650 1550]]


Pregunta 12

In [ ]:
import numpy as np

#Información nutricional (en gramos) respecto a cada alimento
              #Huevo #Jamon
N = np.array([[13, 17], #Proteina
              [11, 5], #Grasa
              [3, 2]]) #Carbohidratos

#Porciones por día necesarias para cumplir con el régimen
              #D1 #D2
C = np.array([[2, 4], #Huevo
              [2, 1]]) #Jamon

R = N@C
print(R)
        

[[60 69]
 [32 49]
 [10 14]]


Pregunta 13

In [ ]:
import numpy as np

#Unidades fabricadas en abril
              #P1 #P2  #P3
I = np.array([[270, 520, 430], #C1
              [380, 290, 600], #C2
              [150, 310, 360]]) #C3

print(I*1.3)


[[351. 676. 559.]
 [494. 377. 780.]
 [195. 403. 468.]]
