# Problema 1

La fábrica de bicicletas Expend produce dos modelos de bicicletas, $M$ y $N$. La matriz $A$ nos indica las cantidades de acero y aluminio que requiere cada bicicleta, expresadas en kg según el modelo a producir, mientras que la matriz $B$ nos entrega un reporte de la cantidad de bicicletas producidas de ambos modelos para los dos primeros meses del año pasado.

<br>

\begin{equation*}
\begin{matrix}
& \begin{matrix}
 & \ \ \ \  M & N
\end{matrix}  \\
&A= \begin{pmatrix}
1 & 2 \\
3 & 2 \\
\end{pmatrix} & \ \begin{matrix}
Acero\\
Aluminio
\end{matrix}\\
\end{matrix}
\ \ \ \ \ \ \ \ \ \ \ \ \ \
\begin{matrix}
& \begin{matrix}
& \ \ \ \ \ \ \ ene & feb &
\end{matrix} & \\
&B= \begin{pmatrix}
290 &  312 \\
 345 &  413 \\
\end{pmatrix} & \begin{matrix}
M\\
N
\end{matrix}\\
\end{matrix}
\end{equation*}

<br>

1. Indique el orden de cada matriz. ¿Es posible determinar la multiplicación entre ambas matrices? Justifique.
2. Determine utilizando *Python* la matriz $C = A \cdot B$
3. Indique e interprete el valor de los elementos $c_{21}$ y $c_{11}$.

In [ ]:
import numpy as np

A = np.array([[1, 2], 
            [3, 2]])

B = np.array([[290, 312],
            [345, 413]])

C = A@B
print(f"La matriz C es: \n{C}")

#1.- Orden matriz A: 2x2
#    Orden matriz B: 2x2
#2.- Matriz C = A * B
#    #ene  #feb
#    [980 1138] - Cantidad de acero en kg
#    [1560 1762] - Cantidad de aluminio en kg
#3.- C21 = 1560 / Indica que se necesitaron 1560kg de aluminio en enero
#    C11 = 980 / Indica que se necesitaron 980kg de acero en enero

La matriz C es: 
[[ 980 1138]
 [1560 1762]]


# Problema 2

Una pequeña cadena tiene restaurantes de comida rápida en Santiago, Concepción y Antofagasta, en los que vende hamburguesas, completos y mateadas. En un fin de semana, las cantidades de cada comida según cada sucursal se distribuyeron de acuerdo con la siguiente matriz $V$, donde las filas corresponden a los productos y las columnas a las sucursales, mientras que los precios, en pesos, de cada producto están expresados en la matriz $P$.

<br>

\begin{split}
V &= \begin{pmatrix}
 1300 &  900  &  800  \\
 2100 &  1700 &  1500 \\
 1500 &  1200 &  900  \\
\end{pmatrix}\\
\\
P &= \begin{pmatrix}
 4200 &  1500 & 3200 \\
\end{pmatrix}
\end{split}

<br>

Si $I = P \cdot V$

1. Indique el orden de cada matriz.
2. Determine utilizando *Python* la matriz $I$.
3. Indique e interprete el valor de los elementos $v_{32}$, $p_{12}$ e $i_{13}$.

In [ ]:
import numpy as np

V = np.array([[1300, 900, 800],
            [2100, 1700, 1500], 
            [1500, 1200, 900]])

P = np.array([[4200, 1500, 3200]])

I = P@V

print(f"La matriz I es: \n{I}")

#1.- Orden matriz V: 3x3
#    Orden matriz P: 1x3
#2.- Matriz I = P*V
#    [13410000 10170000  8490000]
#3.- V32 = 1200 / Se vendieron 1200 malteaadas en Concepción
#    P12 = 1500 / Los completos se venden a $1500
#    I13 = 8490000 / En total se vendieron $8490000 en Antofagasta (entre completos, malteadas y hamburguesas)


La matriz I es: 
[[13410000 10170000  8490000]]


# Problema 3

Una fábrica, para un mismo tipo de artículo eléctrico produce $2$ modelos, $A$ y $B$. Las filas de la matriz $M$, en el orden mencionado, nos muestran la cantidad de transistores y resistores que se requieren por cada artículo, según cada modelo. Por otra parte, las filas de la matriz $Q$ nos reportan las cantidades producidas de cada modelo para las tres primeras semanas del mes pasado.

<br>

\begin{split}
M = \begin{pmatrix}
 9 &  14 \\
 4 &  5  \\
\end{pmatrix} \ \ \ \ \ \ \ \ Q = \begin{pmatrix}
 200 &  240 & 220 \\
 175 &  210 & 215 \\
\end{pmatrix}
\end{split}

<br>

Además, considere las matrices $G = M \cdot Q$ y $H = Q \cdot M$.

1. Indique el orden de $M$ y $Q$.
2. ¿Es posible calcular las matrices $G$ y $H$? Justifique.
3. Determine utilizando *Python* la matriz $G$ e interprete los elementos $g_{23}$  y $g_{12}$.
4. ¿Cuántos resistores se utilizaron durante las tres semanas?

In [6]:
import numpy as np
            #A    #B
M = np.array([[9, 14], #Cantidad de transitores necesarios
            [4, 5]]) #Cantidad de resistores necesarios

            #S1    #S2    #S3
Q = np.array([[200, 240, 220], #Cantidad producida del modelo A
            [175, 210, 215]]) #Cantidad producida del modelo B

G = M@Q
print(f"La matriz G es: \n{G}")

#1.- Orden matriz M: 2x2
#    Orden matriz Q: 2x3
#2.- Es posible calcular M*Q pero no Q*M ya que el número de columnas de M no es igual al número de filas de Q
#3.- Matriz G = M*Q
#    #S1    #S2    #S3
#    [4250 5100 4990] - Cantidad de transistores necesarios
#    [1675 2010 1955] - Cantidad de resistores necesarios
#    G23 = 1955 - Cantidad de resistores necesarios en la semana 3
#    G12 = 5100 - Cantidad de transistores necesarios en la semana 2
#4.- Se utilizaron 5640 resistores durante las 3 semanas 

La matriz G es: 
[[4250 5100 4990]
 [1675 2010 1955]]


# Problema 4

Una empresa de telecomunicaciones necesita optimizar la distribución de su infraestructura de red en Iquique, Santiago y Concepción. Las columnas de la matriz $R$, en el orden mencionado, representan la cantidad de routers y switches que se deben instalar en cada ciudad. La matriz $C$ muestra el costo de instalación, en pesos, de cada router y switch.

<br>

\begin{split}
R = \begin{pmatrix}
 50 &  70 \\
 80 &  110  \\
 60 &  90  \\
\end{pmatrix} \ \ \ \ \ \ C = \begin{pmatrix}
 80000 \\
 45000 \\
\end{pmatrix}
\end{split}

<br>

1. Calcula utilizando *Python* el costo total de instalación para cada ciudad y almacénalo en la matriz $T$.
2. ¿Cuál es la ciudad que tiene mayor costo de instalación?
3. Si se aplica un descuento del $10\%$ en el costo de instalación de los switches, calcula el nuevo costo total de instalación para cada ciudad.

In [ ]:
import numpy as np
            #Routers, Switches
R = np.array([[50, 70], #Iquique
            [80, 110], #Santiago
            [60, 90]]) #Concepción

            #Costo
C = np.array([[80000], #Routerss
            [45000]]) #Switches

T = R@C
print(f"La matriz T es: \n{T}")

D = T*0.9
print(f"La matriz D es: \n{D}")

#1.- T = R*C
#    [7150000] - Iquique
#    [11350000] - Santiago
#    [8850000] - Concepción
#2.- La ciudad con mayor costo de instalación es Santiago con $11350000
#3.- Los nuevos costos se dan por: D = T*0.9
#    [6435000] - Iquique
#    [10215000] - Santiago
#    [7965000] - Concepción



La matriz T es: 
[[ 7150000]
 [11350000]
 [ 8850000]]
La matriz D es: 
[[ 6435000.]
 [10215000.]
 [ 7965000.]]


# Problema 5

Una empresa de servicios en la nube distribuye datos entre tres *Data Center*. La matriz $D$ muestra el volumen de datos (en terabytes) almacenados en cada *Data Center* durante los tres primeros meses del año. Mientras que la matriz $C$ muestra los costos (en dólares) de almacenamiento por terabyte en cada *Data Center*.

<br>

\begin{equation*}
\begin{matrix}
& \begin{matrix}
& \ \ \ \ \ \ \ DC_{1} &   DC_{2} & DC_{3}&
\end{matrix} & \\
&D = \begin{pmatrix}
100 & 150 & 200 \\
120 & 180 & 220 \\
140 & 210 & 250
\end{pmatrix} & \begin{matrix}
Ene\\
Feb\\
Mar
\end{matrix}
\end{matrix}
\ \ \ \ \ \ \ \ \ \ \ \ \ \
\begin{matrix}
& \begin{matrix}
\   
\end{matrix} & \\
&C = \begin{pmatrix}
50 \\
40 \\
30
\end{pmatrix}  \begin{matrix}
DC_{1}\\
DC_{2}\\
DC_{3}
\end{matrix}\\
\end{matrix}
\end{equation*}

<br>

1. Calcula utilizando *Python* la matriz $T = D \cdot C$.
2. Un trabajador indica que en febrero el costo por almacenamiento fue el más alto, ¿es cierta su afirmación?
3. Debido a la inflación, el costo de almacenamiento por terabyte aumenta en un $2,3\%$. Calcula el nuevo costo total de almacenamiento por mes e interprete cada uno de los elementos de la nueva matriz.

In [ ]:
import numpy as np

D = np.array([[100, 150, 200],  
            [120, 180, 220],
            [140, 210, 250]])

C = np.array ([[50], [40], [30]])

T = D@C
print(f"La matriz T es: \n{T}")

T2= T * 1.023
print(f"La matriz T2 es: \n{T2}")

#1.- La matriz T = D*C
#    Costos en dolares de almacenamiento por TB
#    [17000] - Enero
#    [19800] - Febrero
#    [22900] - Marzo
#2.- No es verdadera la afirmación ya que el costo por almacenamiento en marzo es mayor que en febrero
#3.- Debudo a la inflación el costo por almacenamiento aumenta un 2.3% por mes

La matriz T es: 
[[17000]
 [19800]
 [22900]]
La matriz T2 es: 
[[17391. ]
 [20255.4]
 [23426.7]]


# Problema 6

Una compañía que fabrica un determinado producto, tiene $4$ plantas de producción y $5$ bodegas de almacenamiento. La matriz $T$ muestra las unidades de este producto que se generan mensualmente en la planta $i$ y que son transportadas a la bodega $j$, para quedar almacenadas allí durante el mes en que fueron producidas.

Además, la matriz $C$ detalla, para el primer semestre del presente año, el costo unitario (en dólares) de almacenamiento del producto durante el mes $j$ en la bodega $i$.

<br>

\begin{split}
T = \begin{pmatrix}
 500 &  400  &  300 & 200 & 100 \\
 600 &  500  &  400 & 300 & 200 \\
 700 &  600  &  500 & 400 & 300 \\
 800 &  700  &  600 & 500 & 400 \\
\end{pmatrix} \ \ \ \ \ \ C = \begin{pmatrix}
 5 &  6  &  7 &  8  &  9 & 6 \\
 4 &  5  &  6 &  7  &  8 & 7 \\
 3 &  4  &  5 &  6  &  7 & 9 \\
 2 &  3  &  4 &  5  &  6 & 6 \\
 8 &  5  &  6 &  3  &  7 & 5 \\
\end{pmatrix}
\end{split}

<br>

1. Determina la matriz $G = T \cdot C$.
2. Interpreta los elementos $t_{14}$, $c_{53}$ y $g_{35}$.
3. ¿Cuánto cuesta almacenar una unidad del producto en la bodega $4$ durante marzo de este año?
4. ¿Cuánto dinero gasta la empresa por almacenar la producción mensual de la planta $2$ durante el mes de abril?


In [ ]:
import numpy as np

#Unidades de producto que se generan mensualmente en la planta i y que son transportadas a la bodega j
        #Bod 1  #Bod 2  #Bod 3  #Bod 4  #Bod 5
T = np.array([[500, 400, 300, 200, 100], #Planta 1
            [600, 500, 400, 300, 200], #Planta 2
            [700, 600, 500, 400, 300], #Planta 3
            [800, 700, 600, 500, 400]]) #Planta 4

#Costo unitario en dolares de almacenamiento del producto el mes j en la bodega i
#Mes 1  #Mes 2  #Mes 3  #Mes 4  #Mes 5 #Mes 6
C = np.array([[5, 6, 7, 8, 9, 6], #Bod 1
            [4, 5, 6, 7, 8, 7], #Bod 2
            [3, 4, 5, 6, 7, 9], #Bod 3
            [2, 3, 4, 5, 6, 6], #Bod 4
            [8, 5, 6, 3, 7, 5]]) #Bod 5

G = T@C
print(f"La matriz G es: \n{G}")

#1.- La matriz G = T*C
#    Mes 1  Mes 2  Mes 3  Mes 4  Mes 5  Mes 6
#    [6200  7300  8800  9900 11700 10200] - Planta 1
#    [8400  9600 11600 12800 15400 13500] - Planta 2
#    [10600 11900 14400 15700 19100 16800] - Planta 3
#    [12800 14200 17200 18600 22800 20100] - Planta 4
#2.- T14 = 200 / En la planta 1 se generan 200 unidades que son transportadas a la bodega 4
#    C53 = 6 / El costo unitario de almacenamiento en la bodega 5 en el mes 3 es de $6
#    G35 = 16800 / El costo de almacenamiento en la bodega 3 en el mes 5 es de $16800
#3.- Cuesta $4 almacenar una unidad del producto en la bodega 4 en el mes 3
#4.- La empresa gasta $12800 en almacenar la produccion mensual de la planta 2 el 4

La matriz G es: 
[[ 6200  7300  8800  9900 11700 10200]
 [ 8400  9600 11600 12800 15400 13500]
 [10600 11900 14400 15700 19100 16800]
 [12800 14200 17200 18600 22800 20100]]
La suma de la fila 2 de la matriz G es: 71300


# Problema 7

Una empresa dedicada al desarrollo de software, que cuenta con tres sucuersales, necesita renovar los siguientes implementos para su personal: laptop de alto rendimiento, monitor externo de alta resolución, teclado mecánico, mouse ergonómico y disco duro de alta capacidad. Para esto, decide cotizar con tres proveedores y así encontrar el precio más conveniente para realizar la compra. La matriz $F$, en el orden mencionado, indica la cantidad de artículos que necesita comprar para cada sucursal. La matriz $G$ indica el precio unitario (en miles de pesos) de cada producto por proveedor.

<br>

\begin{split}
F = \begin{pmatrix}
 7 &  6  &  15 & 17 & 18 \\
 5 &  10  &  20 & 13 & 12 \\
 8 &  4  &  12 & 18 & 9 \\
\end{pmatrix} \ \ \ \ \ \ G = \begin{pmatrix}
 1700 &  1750 &  1800 \\
  868 &  803  &  840  \\
  165 &  160  &  150  \\
  70  &  73  &   65   \\
  110 &  124  &  115  \\
\end{pmatrix}
\end{split}

<br>

1. Calcula utilizando *Python* la matriz $D = F \cdot G$.
2. Interpreta los elementos $d_{33}$ y $d_{21}$.
3. ¿Cuál es el proveedor más conveniente para realizar todas las compras?
4. Si escoge el proveedor más conveniente, ¿en qué sucursal deberá invertir más dinero por la renovación de los implementos?

In [ ]:
import numpy as np 

#Cantidad de articulos que necesita comprar para cada sucursal
            #L  #MN  #T  #MS  #D
F = np.array([[7, 6, 15, 17, 18], #Sucursal 1
            [5, 10, 20, 13, 12], #Sucursal 2
            [8, 4, 12, 18, 9]]) #Sucursal 3

#Precio unitario (en miles de pesos) de cada producto por proveedor
            #P1     #P2     #P3
G = np.array([[1700, 1750, 1800], #LN
            [868, 803, 840], #MN
            [165, 160, 150], #T
            [70, 73, 65], #MS
            [110, 124, 115]]) #D

D = F@G
print(f"La matriz D es: \n{D}")

P1 = D[0, 0] + D[1, 0] + D[2, 0]
print(f"El total de la compra de la sucursal 1 es: {P1}")

P2 = D[0, 1] + D[1, 1] + D[2, 1]
print(f"El total de la compra de la sucursal 2 es: {P2}")   

P3 = D[0, 2] + D[1, 2] + D[2, 2]
print(f"El total de la compra de la sucursal 3 es: {P3}")

S1 = np.sum(F[0])
print(f"El total de productos de la compra de la sucursal 1 es: {S1}")

S2 = np.sum(F[1])
print(f"El total de productos de la compra de la sucursal 2 es: {S2}")

S3 = np.sum(F[2])
print (f"El total de producto de la compra de la sucursal 3 es: {S3}")

#1.- La matriz D = F*G
#    P1      P2      P3
#    [22753 22941 23065] - Sucursal 1
#    [22710 22417 22625] - Sucursal 2
#    [21302 21562 21765] - Sucursal 3
#2.- D33 = 21765 / Comprar todos los productos de la sucursal 3 cuesta $21765 con el proveedor 3
#    D21 = 22710 / Comprr todos los productos de la sucursal 2 cuesta $22710 con el proveedor 1
#3.- El proveedor 1 es el más conveniente y deberá invertir más en la Sucursal 1 ya que es la que más productos necesita


La matriz D es: 
[[22753 22941 23065]
 [22710 22417 22625]
 [21302 21562 21765]]
El total de la compra de la sucursal 1 es: 66765
El total de la compra de la sucursal 2 es: 66920
El total de la compra de la sucursal 3 es: 67455
El total de productos de la compra de la sucursal 1 es: 63
El total de productos de la compra de la sucursal 2 es: 60
El total de producto de la compra de la sucursal 3 es: 51


# Problema 8

Sea la matriz $A$:

<br>

\begin{split}
A = \begin{pmatrix}
 3 &  1  &  2 \\
 1 &  2  &  1 \\
 4 &  1  &  3 \\
\end{pmatrix}
\end{split}

<br>

1. Calcula, utilizando *Python*, la matriz $A^{-1}$.
2. Calcula la matriz $I = A \cdot A^{-1}$.
3. Calcula la matriz $I^{-1}$. Analiza este resultado, comparando con los resultados obtenidos en los ítems anteriores. ¿Puedes encontrar alguna relación para estas matrices?

# Problema 9

1. Considera que el siguiente sistema de ecuaciones:

<br>

\begin{split}
2x + y & = 7 \\
3x - 2y & = 21
\end{split}

<br>

$\hspace{1cm}$ Se puede escribir matricialmente como:

<br>

\begin{split}
\begin{pmatrix}
 2  &  1 \\
 3 & -2 \\
\end{pmatrix} \cdot \begin{pmatrix}
 x \\
 y \\
\end{pmatrix} = \begin{pmatrix}
 7 \\
 21 \\
\end{pmatrix}
\end{split}

<br>

* Utiliza la matriz inversa para encontrar los valores de $x$ e $y$ que permiten satisfacer ambas ecuaciones simultáneamente.

<br>

2. Considera que el siguiente sistema de ecuaciones:

<br>

\begin{split}
h + m & = 60 \\
0,16h + 0,2m & = 11
\end{split}

<br>

$\hspace{1cm}$ Se puede escribir matricialmente como:

<br>

\begin{split}
\begin{pmatrix}
 1  &  1 \\
 0,16 & 0,2 \\
\end{pmatrix} \cdot \begin{pmatrix}
 h \\
 m \\
\end{pmatrix} = \begin{pmatrix}
 60 \\
 11 \\
\end{pmatrix}
\end{split}

<br>

* Utiliza la matriz inversa para encontrar los valores de $h$ y $m$ que permiten satisfacer el sistema de ecuaciones.

# Problema 10

Considera los siguientes sistemas de ecuaciones:

<br>

**a)**
\begin{split}
2m + 4p & = 2900 \\
3m + 3p & = 3150
\end{split}
<br>
<br>
**b)**
\begin{split}
n + v & = 160 \\
50n + 300v & = 23000
\end{split}

<br>

1. Escribe ambos sistemas de ecuaciones de forma matricial.
1. Utiliza la matriz inversa para calcular las soluciones de ambos sistemas de ecuaciones.




# Problema 11

Una persona tiene $\$8000$ en monedas de $\$10$ y de $50$. El sistema de ecuaciones que representa la situación es el siguiente:

<br>

\begin{split}
x + y & = 200 \\
10x + 50y & = 8000
\end{split}

<br>

1. ¿Qué representa cada variable?
2. Explica qué representa cada una de las ecuaciones del sistema.
3. ¿Cuántas monedas de $\$10$ y de $\$50$ tiene?

# Problema 12

En una granja hay $132$ animales entre patos y vacas. En total hay $402$ patas. El sistema que modela la situación planteada es:

<br>

\begin{split}
p + v & = 132 \\
2p + 4v & = 402
\end{split}

<br>

1. ¿Qué representan las incógnitas del sistema?
2. ¿Cuántos patos hay?

# Problema 13

Luis compró $5$ cables USB y $6$ pendrives, en total canceló $\$82.890$. Pablo compró a los mismos precios $3$ cables USB y $7$ pendrives, y canceló $\$59.900$.

El sistema que modela el problema es:

<br>

\begin{split}
5x + 6y &= 82890 \\
3x +  7y &= 59900
\end{split}

<br>


1. ¿Qué representa cada incógnita en el contexto del problema?
2. Determina cuánto pagaron por cada cable USB.