In [7]:
import numpy as np

F = np.array([[7 ,  6  , 15 ,17 , 18],
              [5 ,  10 ,  20 , 13 , 12],
               [8 ,  4  ,  12 , 18 , 9]])
G = np.array([[1700 , 1750 ,  1800],
                [868 ,  803 ,  840],
                [165 , 160  , 150],
                [70  ,  73  ,   65 ],
                 [110 , 124  , 115 ] ])
D= F@G
print("la Matriz D es :")
print(D)

la Matriz D es :
[[22753 22941 23065]
 [22710 22417 22625]
 [21302 21562 21765]]


la Matriz D es :
Prov1    Prov2   Prov3  
[[22753  22941   23065] sucursal 1
 [ [22710  22417  22625]] sucursal 2
 [21302   21562   21765]] sucursal 3

Interpreta los elementos $d_{33}$ y $d_{21}$.

d33= 21765 # comprar todos los productos con el Proveedor 3 para sucursal 3 tiene un costo de $21.765.000
d21= 22710 # comprar todos los productos con el Proveedor 1 para sucursal 2 tiene un costo de $22.710.000

In [6]:
Proveedor_1= 22753+22710+21302
Proveedor_2=22941+22417+21562
Proveedor_3=23065+22625+21765
print(Proveedor_1)
print(Proveedor_2)
print(Proveedor_3)
print("el proveedor más barato es el 1 con $66.765.000")

66765
66920
67455
el proveedor más barato es el 1 con $66.765.000


In [17]:
import numpy as np
A = np.array([[3,1,2],
              [1,2,1],
               [4,1,3]])

A_inv = np.linalg.inv(A) #Código para determinar la inversa
I= np.round(A@A_inv)
print(A_inv)
print()
I_inv=np.linalg.inv(I) #Código para determinar la inversa

print()
print(I)
print()
print(I_inv)


[[ 2.5 -0.5 -1.5]
 [ 0.5  0.5 -0.5]
 [-3.5  0.5  2.5]]


[[ 1. -0.  0.]
 [ 0.  1.  0.]
 [ 0. -0.  1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
import numpy as np
A = np.array([[3,1],
              [-2,4]])
B= np.array([[7],
             [7]])
Ain=np.linalg.inv(A)
soluciones=(Ain@B)
print(soluciones)

[[1.5]
 [2.5]]
