# Análisis de Datos Olímpicos: Puntuaciones y Proyecciones Matemáticas

Durante los Juegos Olímpicos de París 2024, se registraron las puntuaciones máximas de los equipos de Estados Unidos, China y Francia en tres disciplinas deportivas: gimnasia artística, saltos ornamentales (clavados) y tiro con arco.

El evento deportivo tuvo una duración de tres semanas, y se registraron las puntuaciones en las dos primeras semanas. Las matrices $A$ y $B$ representan las puntuaciones máximas de las semanas $1$ y $2$, respectivamente:

<center>
<img src="https://i.imgur.com/VkCRY9T.png" style="width:50%">
</center>

Donde los elementos $a_{ij}$ y $b_{ij}$ representan los puntos obtenidos por el país $i$ en la disciplina deportiva $j$, siguiendo el mismo orden en que se mencionaron en el párrafo anterior.

Utiliza Python para responder las siguientes preguntas:

1. Determina si los países mejoraron su desempeño en cada disciplina durante la segunda semana con respecto a la primera semana. Muestra los resultados en una matriz $D$ e interpreta el elemento $d_{23}$.
1. Después de semanas de competencia la motivación de los deportistas se encuentra en su punto más alto. Debido a esto, analistas deportivos estimaron que en la tercera semana los deportistas podrían mejorar su rendimiento en torno a un $4\%$ respecto a la primera semana. Representa los resultados que se proyectan para la última semana en la matriz $E$  e interpreta el elemento $e_{21}$. Redondea los resultados a la centésima.
1. Uno de los criterios para determinar el país ganador en las Olimpiadas consiste en asignar puntos a cada tipo de medalla: $3$ puntos por una medalla de oro, $2$ puntos por una medalla de plata y $1$ punto por una medalla de bronce. Luego, se suman los puntos totales para determinar al país con mayor puntaje. Considera que los elementos $f_{ij}$ de la matriz $F$, según el orden en que se mencionan, representan el total de medallas de cada tipo $j$ (oro, plata y bronce) obtenidas por el país $i$ (Estados Unidos, China y Francia). Por otro lado, la matriz $G$ representa el puntaje asignado según el tipo de medalla.

<center>
<img src="https://i.imgur.com/bPCKq7i.png" style="width:35%">
</center>

$\hspace{0.5 cm}$ Representa mediante una matriz $H$ el puntaje total obtenido por cada país e interpreta la diferencia $h_{11} - h_{21}$.

4. Durante esta edición de los Juegos Olímpicos, un país obtuvo un total de $12$ medallas entre oro, plata y bronce, logrando un puntaje total de $18$ puntos ($3$ puntos por cada medalla de oro, $2$ puntos por cada medalla de plata y $1$ punto por cada medalla de bronce). Además, los deportistas de este país recibieron un aporte estatal de $52$ millones de pesos por cada medalla de oro, $39$ millones de pesos por cada medalla de plata y $19$ millones de pesos por cada medalla de bronce. Con estos datos, se plantea el siguiente sistema de ecuaciones:

<center>
<img src="https://i.imgur.com/jCNlXyF.png" style="width:26%">
</center>


$\hspace{0.5 cm}$ Donde $x$, $y$ y $z$ representan la cantidad de medallas de oro, plata y bronce obtenidas por el país. Resuelve el sistema de ecuaciones utilizando matrices e interpreta los resultados obtenidos en el contexto del problema.

In [1]:
import numpy as np

             #G.A  #CLAV  #T.A
A = np.array([[9.2, 9.1, 8.7], #EE.UU
              [9.4, 9.5, 9.0], #China
              [8.9, 9.4, 9.1]]) #Francia

B = np.array([[9.4, 9.3, 9.0], #EE.UU
              [9.6, 9.7, 9.1], #China
              [8.7, 9.2, 9.5]]) #Francia

D = B - A

E = A * 1.04

print(D)

print(E.round(2))

            #T.O  #T.P  #T.B
F = np.array([[45, 38, 29], #EE.UU
              [38, 32, 25], #China
              [33, 17, 19]]) #Francia
    #PTJE  
G = ([[3], #O
      [2], #P
      [1]]) #B

H = F@G

print (H)

I = np.array([[1, 1, 1],
              [3, 2, 1], 
              [52, 39, 19]])

J = np.array([[12], 
              [18],
              [341]])

I_i = np.linalg.inv(I)
 
K = I_i @ J

print(K)


[[ 0.2  0.2  0.3]
 [ 0.2  0.2  0.1]
 [-0.2 -0.2  0.4]]
[[9.57 9.46 9.05]
 [9.78 9.88 9.36]
 [9.26 9.78 9.46]]
[[240]
 [203]
 [152]]
[[1.]
 [4.]
 [7.]]


In [ ]:
# 1.- D = B - A
#  G.A  CLAV  T.A
# [ 0.2  0.2  0.3] EE.UU
# [ 0.2  0.2  0.1] China
# [-0.2 -0.2  0.4] Francia
# Los paises mejoraron su desempeño la segunda semana a excepción de Francia en gimnasia artística y clavaos que diminuyó 0.2 puntos en ambas disciplinas
# D23 = 0.1 / Indica que China mejoró su desempeño en tiro con arco en 0.1 la segunda semana en comparación a la primera

# 2.- E = A * 1.04
#  G.A  CLAV  T.A
# [9.57 9.46 9.05] EE.UU
# [9.78 9.88 9.36] China
# [9.26 9.78 9.46] Francia
# E21 = 9.78 / Indica que China mejoró en 0.38 en gimnasia artística la tercera semana en comparación a la primera

#3.- H = F * G
#   PTJE 
#  [240] EE.UU
#  [203] China
#  [152] Francia
# H11 - H21 = 37 / Indica que EE.UU obtuvo 37 puntos más que China en los JJ.OO

# 4.- K = I_i @ J
# Cantidad de medallas obtenidas
# [1] Oro
# [4] Plata
# [7] Bronce